services:
  user-service:
    image: amalskr/bewellness:user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/bw_user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  chat-service:
    image: amalskr/bewellness:chat-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/bw_chat
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  booking-service:
    image: amalskr/bewellness:booking-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/bw_booking
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

  api-gateway:
    image: amalskr/bewellness:api-gateway
    ports:
      - "8090:8090"
    environment:
      GATEWAY_ROUTE_TIMEOUT: 30s